FROM apache/airflow:2.7.1-python3.9

USER root
RUN apt-get update && apt-get install -y curl gcc python3-dev

USER airflow
RUN pip install --user --upgrade pip
RUN pip install --user pandas numpy psycopg2-binary sqlalchemy requests

USER root
